// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSTQ5IkUORELDcIJudXyTh1I8FnvFrIyc',
    appId: '1:121294387458:web:8aba49595aca22d6ef6a1b',
    messagingSenderId: '121294387458',
    projectId: 'mehreen-backend',
    authDomain: 'mehreen-backend.firebaseapp.com',
    storageBucket: 'mehreen-backend.firebasestorage.app',
    measurementId: 'G-2X4Z0G6EYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-65_Ou4PhOyQJJ9wycW-XeX083vG_4KA',
    appId: '1:121294387458:android:fbca0b187007abcbef6a1b',
    messagingSenderId: '121294387458',
    projectId: 'mehreen-backend',
    storageBucket: 'mehreen-backend.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSTQ5IkUORELDcIJudXyTh1I8FnvFrIyc',
    appId: '1:121294387458:web:7a76161e5c4cb2eaef6a1b',
    messagingSenderId: '121294387458',
    projectId: 'mehreen-backend',
    authDomain: 'mehreen-backend.firebaseapp.com',
    storageBucket: 'mehreen-backend.firebasestorage.app',
    measurementId: 'G-61C6G0N0B2',
  );
}
